packages:
  # all packages in direct subdirs of packages/
  - 'frontend/**'
  # all packages in subdirs of components/
  - 'backend/**'
  # exclude packages that are inside test directories
  - '!**/test/**'